import type { NpcSpec } from "../entities/Npc";
import type { MapKey } from "../maps";
import type { RoomKey } from "../rooms";
import type { OverlayKey } from "@/lib/store/gameStore";

/** A talkable prop — a sign, a screen, a machine. Sits on its own tile; the player stands beside it. */
export interface ObjectSpec {
  label: string;
  col: number;
  row: number;
  /** Unattributed narration lines (no speaker name in the box). */
  lines: string[];
  /**
   * Panel this prop opens once its lines are read. Machines the player operates
   * (the Pump terminal, later the shop builder) are real screens, not dialogue —
   * the lines introduce them, the panel does the work.
   */
  opens?: OverlayKey;
}

/** An area that speaks the moment the player walks in. Tiles, like everything else here. */
export interface ZoneSpec {
  col: number;
  row: number;
  w: number;
  h: number;
  once?: boolean;
  lines: string[];
}

export interface AreaInteractions {
  npcs?: NpcSpec[];
  objects?: ObjectSpec[];
  zones?: ZoneSpec[];
}

/**
 * Everything the player can talk to, per overworld map. Kept out of the map
 * JSON on purpose: those files are regenerated by scripts/build-city.py, which
 * would wipe hand-authored content. Tile coordinates here are checked against
 * the generated collision layout — see the walkability note in build-city.py.
 */
export const MAP_INTERACTIONS: Partial<Record<MapKey, AreaInteractions>> = {
  "town-main": {
    npcs: [
      {
        sheet: "amelia",
        name: "Wren",
        col: 12,
        row: 30,
        facing: "right",
        lines: [
          "You're the one from Aleph-Null, aren't you.",
          "Your elixir went cloudy the same night ours did. Nobody here thinks that's a coincidence.",
          "The Pump is north-east, past the bridges. That's where progress actually gets recorded.",
        ],
      },
      {
        sheet: "bob",
        name: "Halden",
        col: 32,
        row: 20,
        facing: "down",
        lines: [
          "Careful how you spend the day. The bar drains whether you're working or not.",
          "Grinding here doesn't move it. Only a proven spend does.",
        ],
      },
      {
        sheet: "alex",
        name: "Sable",
        col: 37,
        row: 32,
        facing: "left",
        lines: [
          "People keep asking me how to fool the bar.",
          "You can. Go ahead. Edit whatever you like — the world just won't move.",
          "It only moves on something that really happened. That's the whole trick.",
        ],
      },
    ],
  },
  "town-b": {
    npcs: [
      {
        sheet: "bob",
        name: "Corin",
        col: 32,
        row: 19,
        facing: "down",
        lines: [
          "Second universe, same rot. We're further along the drain than you are.",
          "Don't hoard what you earn. Unspent elixir does nothing for anybody.",
        ],
      },
      {
        sheet: "amelia",
        name: "Iva",
        col: 11,
        row: 30,
        facing: "right",
        lines: ["Trade's dead until the bars come back up.", "Ask at the hall — they keep the records."],
      },
    ],
  },
  "town-c": {
    npcs: [
      {
        sheet: "alex",
        name: "Otho",
        col: 13,
        row: 16,
        facing: "down",
        lines: [
          "You came the long way round, over the west bridge.",
          "Everyone does. The roads were built before the island was.",
        ],
      },
      {
        sheet: "bob",
        name: "Rell",
        col: 36,
        row: 46,
        facing: "up",
        lines: ["Three universes, three bars, one Pump.", "Make of that what you like."],
      },
    ],
  },
  pump: {
    npcs: [
      {
        sheet: "amelia",
        name: "Keeper Aisley",
        col: 9,
        row: 15,
        facing: "right",
        lines: [
          "Welcome to the island. The Pump doesn't take promises — it takes proof.",
          "Spend your elixir for real, bring back the receipt, and your universe moves.",
          "It takes a few minutes to come through. That wait is the honest part.",
        ],
      },
    ],
    zones: [
      {
        col: 15,
        row: 8,
        w: 6,
        h: 2,
        once: true,
        lines: [
          "The air over the island hums — every universe's progress passes through this one building.",
        ],
      },
    ],
  },
};

/**
 * Interior content, keyed by room. Coordinates are floor tiles (0,0 = the
 * top-left walkable tile), matching `rooms.ts`.
 */
export const ROOM_INTERACTIONS: Partial<Record<RoomKey, AreaInteractions>> = {
  home: {
    objects: [
      { label: "Bed", col: 1, row: 2, lines: ["Your bed. Rest doesn't refill the bar — nothing here does."] },
      {
        label: "Screen",
        col: 6,
        row: 1,
        lines: ["The broadcast loops the same three bars, all sinking at slightly different rates."],
      },
    ],
  },
  shop: {
    npcs: [
      {
        sheet: "bob",
        name: "Merrit",
        col: 6,
        row: 3,
        facing: "down",
        lines: ["Stock's thin.", "Bring me tokens that cleared the Pump and we'll talk properly."],
      },
    ],
    objects: [{ label: "Counter", col: 3, row: 5, lines: ["A ledger, open, mostly blank."] }],
  },
  lounge: {
    npcs: [
      {
        sheet: "amelia",
        name: "Juno",
        col: 6,
        row: 3,
        facing: "down",
        lines: ["Sit if you like. Half this town is waiting on an attestation anyway."],
      },
    ],
    objects: [{ label: "Screen", col: 6, row: 1, lines: ["Static, with the season standings crawling underneath."] }],
  },
  hall: {
    npcs: [
      {
        sheet: "bob",
        name: "Clerk Odell",
        col: 5,
        row: 2,
        facing: "down",
        lines: [
          "Records office. We log what the Pump confirms, nothing else.",
          "If it isn't proven, as far as this hall is concerned it didn't happen.",
        ],
      },
    ],
    objects: [{ label: "Records", col: 1, row: 2, lines: ["Ledgers going back further than the corruption does."] }],
  },
  pump: {
    npcs: [
      {
        sheet: "alex",
        name: "Technician Vey",
        col: 8,
        row: 4,
        facing: "down",
        lines: [
          "Terminal's yours when you have something to submit.",
          "Don't stand there watching it. Verification takes minutes, not seconds.",
        ],
      },
    ],
    objects: [
      {
        label: "Pump terminal",
        col: 5,
        row: 6,
        opens: "pump",
        lines: ["THE ELIXIR PUMP — mint what you earned, then prove what you spend."],
      },
    ],
  },
};
